# Generated by Django 2.2.6 on 2019-12-09 15:05

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='hinhsp',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.tai_len_file_image),
        ),
    ]
