# Generated by Django 2.2.6 on 2019-12-12 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_hinhsp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
