# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-24 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20191224_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='hinhsp',
        ),
    ]
