# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-29 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=b'abc'),
        ),
    ]
